"""empty message

Revision ID: 8aac18bf0f74
Revises: 938df39cf4b9
Create Date: 2025-05-12 11:47:10.116186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aac18bf0f74'
down_revision = '938df39cf4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_to_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
